Added TSG for security vulnerability CVE 2024-49060
Azure/AzureStackHCI-Supportability pull request #16
Opened 2024-11-12 16:28 UTC by alkohli

2024-11-12 17:41 UTC, kerimhanif commented on TSG/ArcVMs/security-vulnerability-cve-2024-49060.md
> +Arc VMs running releases prior to Azure Stack HCI, 2411 release are vulnerable.
Do we have the comma in the right place here?

2024-11-12 17:43 UTC, kerimhanif commented on TSG/ArcVMs/security-vulnerability-cve-2024-49060.md
> +To ensure ongoing protection for newly provisioned VMs, update to the latest 2411 release. This release includes a fix that prevents this vulnerability for newly provisioned VMs, eliminating the need
Let's change "This release includes a fix" to "This release includes fixes"

2024-11-12 17:44 UTC, kerimhanif commented on TSG/ArcVMs/security-vulnerability-cve-2024-49060.md
> +To mitigate this vulnerability, first identify all the Arc VMs created before the Azure Stack HCI, 2411 release. Then, change the account password on each VM.
Again the comma sounds better here but still is it correctly placed?

2024-11-12 17:45 UTC, kerimhanif commented on TSG/ArcVMs/security-vulnerability-cve-2024-49060.md
> +1. Identify all the Arc VMs created before the Azure Stack HCI, 2411 release, run the following script. Make sure to change the variables in the beginning with the appropriate values.
"the variables in the beginning" to "the variables in the beginning of the script"

2024-11-12 17:46 UTC, kerimhanif commented on TSG/ArcVMs/security-vulnerability-cve-2024-49060.md
> +    # Format the table and flag VMs that are updated before the update date
"flag VMs that are" to "flag VMs that were"

2024-11-12 17:47 UTC, kerimhanif requested changes
Added some comments and change requests

2024-11-15 01:28 UTC, charlesjoy approved these changes

2024-11-15 01:29 UTC, merged